"""promptlibretto — registry-based prompt model + runtime."""
from __future__ import annotations

from .config import GenerationConfig
from .output.processor import OutputPolicy, OutputProcessor, ValidationResult
from .providers.base import (
    ProviderAdapter,
    ProviderRequest,
    ProviderResponse,
    ProviderStreamChunk,
    StreamingProviderAdapter,
    supports_streaming,
)
from .providers.mock import MockProvider
from .providers.ollama import OllamaProvider
from .memory import (
    Amendment,
    Classifier,
    ClassifierResult,
    DebtEntry,
    EmotionalState,
    EmotionalStateLayer,
    Episode,
    EpisodeChunk,
    EpisodeStore,
    MemoryAction,
    MemoryChunk,
    MemoryDebtLayer,
    MemoryEngine,
    MemoryGenerationResult,
    MemoryRule,
    MemoryStore,
    MemoryTurn,
    OllamaEmbedder,
    PersonalityLayer,
    PersonalityProfile,
    PreparedMemoryState,
    ReflectionEntry,
    RelationshipLayer,
    RelationshipProfile,
    Router,
    SystemSummary,
    SystemSummaryLayer,
    WorkingNotes,
    WorkingNotesLayer,
    apply_style_blend,
    boosted_confidence,
    decayed_confidence,
    hedge,
)
from .registry import (
    BaseItem,
    derive_state_schema,
    SelectableItem,
    SectionStateSchema,
    StateSchema,
    ContextItem,
    Display,
    DynamicMixin,
    Engine,
    Fragment,
    GenerationChunk,
    GenerationResult,
    Group,
    Item,
    OutputDirection,
    Persona,
    PromptEnding,
    Registry,
    RegistryState,
    Route,
    RuntimeInjection,
    SCHEMA_VERSION,
    SECTION_KEYS,
    WELL_KNOWN_SECTIONS,
    Scale,
    ScalableMixin,
    Section,
    SectionState,
    Sentiment,
    StaticInjection,
    export_json,
    hydrate,
    load_registry,
)

__all__ = [
    # Engine
    "Engine",
    "GenerationChunk",
    "GenerationResult",
    # State
    "RegistryState",
    "SectionState",
    # Registry
    "Registry",
    "Route",
    "Section",
    "SCHEMA_VERSION",
    "SECTION_KEYS",
    "WELL_KNOWN_SECTIONS",
    "export_json",
    "hydrate",
    "load_registry",
    # Core building blocks
    "BaseItem",
    "Display",
    "DynamicMixin",
    "Fragment",
    "Scale",
    "ScalableMixin",
    # Item types
    "Item",
    "ContextItem",
    "Group",
    "OutputDirection",
    "Persona",
    "PromptEnding",
    "RuntimeInjection",
    "Sentiment",
    "StaticInjection",
    # State schema
    "StateSchema",
    "SectionStateSchema",
    "SelectableItem",
    "derive_state_schema",
    # Providers
    "ProviderAdapter",
    "ProviderRequest",
    "ProviderResponse",
    "ProviderStreamChunk",
    "StreamingProviderAdapter",
    "supports_streaming",
    "MockProvider",
    "OllamaProvider",
    # Config + output
    "GenerationConfig",
    "OutputPolicy",
    "OutputProcessor",
    "ValidationResult",
    # Memory
    "MemoryEngine",
    "MemoryGenerationResult",
    "PreparedMemoryState",
    "MemoryStore",
    "MemoryTurn",
    "MemoryChunk",
    "Classifier",
    "ClassifierResult",
    "Router",
    "MemoryAction",
    "MemoryRule",
    "Episode",
    "EpisodeChunk",
    "EpisodeStore",
    "EmotionalState",
    "EmotionalStateLayer",
    "MemoryDebtLayer",
    "DebtEntry",
    "PersonalityLayer",
    "PersonalityProfile",
    "Amendment",
    "RelationshipLayer",
    "RelationshipProfile",
    "ReflectionEntry",
    "SystemSummary",
    "SystemSummaryLayer",
    "WorkingNotes",
    "WorkingNotesLayer",
    "OllamaEmbedder",
    "apply_style_blend",
    "boosted_confidence",
    "decayed_confidence",
    "hedge",
]
