from __future__ import annotations

import re
from dataclasses import asdict
from typing import Any, Mapping, Optional, Sequence

from .builders.builder import BuildContext, GenerationRequest
from .builders.composite import CompositeBuilder
from .config import GenerationConfig
from .runtime.engine import PromptEngine


_INPUT_MARKER = "__PROMPTLIBRETTO_INPUT__"
_DEFAULT_CONFIG = GenerationConfig()


def export_python(
    engine: PromptEngine,
    *,
    route: Optional[str] = None,
    injections: Sequence[str] = (),
    include_overlays: bool = True,
    section_overrides: Optional[Mapping[str, str]] = None,
) -> str:
    route_name = route or engine.router._default or (engine.router.routes()[0].name)
    route_obj = engine.router.get(route_name)
    if route_obj is None:
        raise ValueError(f"unknown route: {route_name!r}")
    builder = route_obj.builder
    if not isinstance(builder, CompositeBuilder):
        raise TypeError(
            f"export_python only supports CompositeBuilder routes (got {type(builder).__name__})"
        )

    snapshot = engine.context_store.get_state()
    request = GenerationRequest(
        mode=route_name,
        inputs={"input": _INPUT_MARKER},
        injections=tuple(injections),
    )
    materialized = engine._materialize_injections(request.injections)
    ctx = BuildContext(
        snapshot=snapshot,
        request=request,
        assets=engine.asset_registry,
        random=engine.random,
        injections=materialized,
    )

    system_parts = [s(ctx) for s in builder.system_sections]
    user_parts = [s(ctx) for s in builder.user_sections]
    if section_overrides:
        sep = builder.separator or "\n\n"
        if "system" in section_overrides:
            system_parts = _split_override(section_overrides["system"], sep)
        if "user" in section_overrides:
            user_parts = _split_override(section_overrides["user"], sep)

    lines: list[str] = []
    lines.append("# Generated by promptlibretto.export_python")
    lines.append("from promptlibretto import PromptEngine")
    needs_overlay_import = include_overlays and bool(snapshot.overlays)
    if needs_overlay_import:
        lines.append("from promptlibretto import ContextOverlay")
    lines.append("")

    config_dict = _nondefault_config(engine.config)
    config_literal = _format_dict(config_dict, indent=8) if config_dict else "{}"

    system_literals = [_format_section(p) for p in system_parts if p.strip()]
    user_literals = [_format_section(p) for p in user_parts if p.strip()]

    route_body_lines: list[str] = []
    if system_literals:
        route_body_lines.append("        \"system_sections\": [")
        for lit in system_literals:
            route_body_lines.append(f"            {lit},")
        route_body_lines.append("        ],")
    if user_literals:
        route_body_lines.append("        \"user_sections\": [")
        for lit in user_literals:
            route_body_lines.append(f"            {lit},")
        route_body_lines.append("        ],")
    if builder.generation_overrides:
        route_body_lines.append(
            "        \"generation_overrides\": "
            + _format_dict(dict(builder.generation_overrides), indent=12) + ","
        )
    if builder.output_policy:
        route_body_lines.append(
            "        \"output_policy\": "
            + _format_dict(dict(builder.output_policy), indent=12) + ","
        )

    lines.append("engine = PromptEngine(")
    if config_dict:
        lines.append(f"    config={config_literal},")
    if snapshot.base:
        lines.append(f"    context_store={_repr_str(snapshot.base)},")
    lines.append("    routes={")
    lines.append(f"        {_repr_str(route_name)}: {{")
    lines.extend(route_body_lines)
    lines.append("        },")
    lines.append("    },")
    lines.append(")")

    sorted_overlays = sorted(
        snapshot.overlays.items(), key=lambda kv: -kv[1].priority
    ) if (include_overlays and snapshot.overlays) else []

    runtime_slots: list[tuple[str, Any, str]] = []
    fixed_overlays: list[tuple[str, Any]] = []
    for name, overlay in sorted_overlays:
        mode = str((overlay.metadata or {}).get("runtime") or "").lower()
        if mode in ("optional", "required"):
            runtime_slots.append((name, overlay, mode))
        else:
            fixed_overlays.append((name, overlay))

    if fixed_overlays:
        lines.append("")
        for name, overlay in fixed_overlays:
            args = [f"text={_repr_str(overlay.text)}"]
            if overlay.priority:
                args.append(f"priority={overlay.priority}")
            if overlay.expires_at is not None:
                args.append(f"expires_at={overlay.expires_at!r}")
            if overlay.metadata:
                args.append(f"metadata={_format_dict(dict(overlay.metadata), indent=0)}")
            lines.append(
                f"engine.context_store.set_overlay({_repr_str(name)}, "
                f"ContextOverlay({', '.join(args)}))"
            )

    lines.append("")
    lines.append("")
    fixed_overlay_names = [n for n, _ in fixed_overlays]
    lines.extend(_emit_run_wrapper(runtime_slots, fixed_overlay_names))

    return "\n".join(lines) + "\n"


def _emit_run_wrapper(
    runtime_slots: Sequence[tuple[str, Any, str]],
    fixed_overlay_names: Sequence[str] = (),
) -> list[str]:
    required = [(n, o) for n, o, m in runtime_slots if m == "required"]
    optional = [(n, o) for n, o, m in runtime_slots if m == "optional"]
    needs_overlay_import = bool(runtime_slots)

    lines: list[str] = []
    if needs_overlay_import:
        lines.append("from promptlibretto import ContextOverlay  # re-import for run()")
        lines.append("")

    sig_parts = ["user_input: str = \"\""]
    if required or optional:
        sig_parts.append("*")
    for name, _ in required:
        sig_parts.append(f"{_py_ident(name)}: str")
    for name, _ in optional:
        sig_parts.append(f"{_py_ident(name)}: str = \"\"")
    sig_parts.append("**extra: str")
    sig = ", ".join(sig_parts)

    lines.append(f"async def run({sig}):")
    doc = ['"""Call the tuned engine with runtime context.']
    if required:
        doc.append("")
        doc.append("Required runtime slots:")
        for name, overlay in required:
            doc.append(f"  - {name} (priority {overlay.priority})")
    if optional:
        doc.append("")
        doc.append("Optional runtime slots:")
        for name, overlay in optional:
            doc.append(f"  - {name} (priority {overlay.priority})")
    doc.append("")
    doc.append("Any extra keyword arguments are attached as priority-10 overlays.")
    doc.append('"""')
    for line in doc:
        lines.append(f"    {line}")

    # Reset stale runtime / extra overlays from prior calls so each
    # invocation starts clean. Fixed overlays are preserved.
    keep_names = set(fixed_overlay_names)
    lines.append(
        f"    _keep = {sorted(keep_names)!r}"
    )
    lines.append(
        "    for _name in list(engine.context_store.overlays()):"
    )
    lines.append("        if _name not in _keep:")
    lines.append("            engine.context_store.clear_overlay(_name)")

    for name, overlay in required:
        ident = _py_ident(name)
        lines.append(f"    if not {ident}:")
        lines.append(
            f"        raise ValueError(\"runtime slot {name!r} is required\")"
        )
        lines.append(
            f"    engine.context_store.set_overlay({_repr_str(name)}, "
            f"ContextOverlay(text={ident}, priority={overlay.priority}))"
        )
    for name, overlay in optional:
        ident = _py_ident(name)
        lines.append(f"    if {ident}:")
        lines.append(
            f"        engine.context_store.set_overlay({_repr_str(name)}, "
            f"ContextOverlay(text={ident}, priority={overlay.priority}))"
        )
    lines.append("    for _name, _value in extra.items():")
    lines.append("        if _value:")
    lines.append(
        "            engine.context_store.set_overlay(_name, "
        "ContextOverlay(text=str(_value), priority=10))"
    )
    lines.append("    return await engine.generate_once(user_input)")
    return lines


def _split_override(text: str, sep: str) -> list[str]:
    parts = [p.strip() for p in text.split(sep)]
    return [p for p in parts if p]


def _py_ident(name: str) -> str:
    import keyword as _kw
    import re as _re
    cleaned = _re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not cleaned or cleaned[0].isdigit():
        cleaned = "_" + cleaned
    if _kw.iskeyword(cleaned):
        cleaned += "_"
    return cleaned


def _nondefault_config(config: GenerationConfig) -> dict[str, Any]:
    out: dict[str, Any] = {}
    defaults = asdict(_DEFAULT_CONFIG)
    for k, v in asdict(config).items():
        if v != defaults.get(k):
            out[k] = v
    return out


def _format_section(rendered: str) -> str:
    if _INPUT_MARKER not in rendered:
        return _repr_str(rendered)
    prefix, suffix = rendered.split(_INPUT_MARKER, 1)
    return (
        f"lambda ctx, _p={prefix!r}, _s={suffix!r}: "
        f"_p + str(ctx.request.inputs.get('input', '')) + _s"
    )


def _repr_str(s: str) -> str:
    if "\n" in s:
        escaped = s.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
        return f'"""{escaped}"""'
    return repr(s)


def _format_dict(d: Mapping[str, Any], *, indent: int) -> str:
    if not d:
        return "{}"
    pad = " " * indent
    inner_pad = " " * (indent + 4) if indent else "    "
    close_pad = pad
    lines = ["{"]
    for k, v in d.items():
        lines.append(f"{inner_pad}{_repr_str(str(k))}: {_repr_value(v)},")
    lines.append(f"{close_pad}}}")
    return "\n".join(lines)


def _repr_value(v: Any) -> str:
    if isinstance(v, str):
        return _repr_str(v)
    if isinstance(v, Mapping):
        return _format_dict(dict(v), indent=0)
    if isinstance(v, (list, tuple)):
        items = ", ".join(_repr_value(x) for x in v)
        return f"[{items}]"
    return repr(v)
